version: '3'

name: icfts
services:
    preprocess:
        build:
            context: app/
            dockerfile: ./../docker/Dockerfile-preprocess
        environment:
            PYTHONUNBUFFERED: 1
        volumes:
            # - '${DATA_PATH}:/data/'
            - './app/data-test/:/data/'

    frontend:
        build:
            context: app/
            dockerfile: ./../docker/Dockerfile-frontend
        volumes:
            - './app/frontend:/app'
            - '/app/node_modules/'
        ports:
            - 4200:4200
        # depends_on:
        #     preprocess:
        #         condition: service_completed_successfully

    backend:
        build:
            context: app/
            dockerfile: ./../docker/Dockerfile-backend
        volumes:
            - './app/backend:/app'
            - '/app/__pycache__/'
            - '${DATA_PATH}:/data/'
        ports:
            - 8000:8000
        environment:
            PYTHONUNBUFFERED: 1
        # depends_on:
        #     preprocess:
        #         condition: service_completed_successfully

