name: icfts
services:
    preprocess:
        tty: true
        build:
            context: app/
            dockerfile: ./../docker/Dockerfile-preprocess
        environment:
            - HOST_UID=${UID}
            - HOST_GID=${GID}
            - PYTHONUNBUFFERED=1
        volumes:
            - '${DATA_PATH}:/data/'

    frontend:
        build:
            context: app/
            dockerfile: ./../docker/Dockerfile-frontend
        volumes:
            - './app/frontend:/app'
            - '/app/node_modules/'
        ports:
            - 4200:4200
        depends_on:
            # preprocess:
            #     condition: service_completed_successfully
            backend:
                condition: service_healthy

    backend:
        build:
            context: app/
            dockerfile: ./../docker/Dockerfile-backend
        volumes:
            - './app/backend:/app'
            - '/app/__pycache__/'
            - '${DATA_PATH}:/data/'
        ports:
            - 8000:8000
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8000/']
            interval: 300s
            timeout: 10s
            retries: 3
        environment:
            PYTHONUNBUFFERED: 1
        # depends_on:
        #     preprocess:
        #         condition: service_completed_successfully

