# Use the official Node.js version 21 image as the base image
FROM node:22

# Create a directory named 'app' in the container filesystem
RUN mkdir /app

# Set the working directory to '/app' within the container
WORKDIR /app

# Copy all contents from the local 'frontend' directory to the '/app' directory in the container
COPY frontend/ /app/

# Install dependencies using yarn package manager
RUN yarn

# Install angular
RUN yarn global add @angular/cli 

# Build the frontend application
RUN yarn build

# Expose port 4200 to allow external access to the application
EXPOSE 4200

# Define the default command to execute when the container starts
CMD ["yarn", "start"]
